### ISSUE TITLE
Retry Sends?

### ISSUE THREAD

**Issue by zx48** [datalust/seq-apps#101]
We now and again get a send issue from the app like this:

System.Net.Mail.SmtpException: Error in processing. The server response was: 4.3.111 Temporary server error. Please try again later MRH1 [Hostname=GVXP192MB1782.EURP192.PROD.OUTLOOK.COM]
   at System.Net.Mail.DataStopCommand.CheckResponse(SmtpStatusCode statusCode, String serverResponse)
   at System.Net.Mail.DataStopCommand.Send(SmtpConnection conn)
   at System.Net.Mail.SmtpClient.Send(MailMessage message)
   at Seq.App.EmailPlus.EmailApp.On(Event`1 evt) in C:\projects\seq-apps\src\Seq.App.EmailPlus\EmailApp.cs:line 145
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 132

Would it be possible to have it retry on a backoff? (for example using Polly)

**Comment by liammclennan** [comment]
Hi @cjindustries,

That is an interesting idea and I think it is possible. In your particular circumstance are you able to gather from O365 why the server rejects the mail? Many of the possible reasons seem like things that won't be helped by a retry (mailbox full etc).

**Comment by nblumhardt** [comment]
In case it helps in the meantime: https://serverfault.com/questions/1102376/error-sending-email-with-office-365 has some configuration suggestions on the O365 end.
