### ISSUE TITLE
The type initializer for 'TimeZoneConverter.TZConvert' threw an exception

### ISSUE THREAD

**Issue by c0shea** [datalust/seq-apps#105]
We upgraded to Seq 2023.1.8948 the other day and since then we are unable to send emails using the Seq.App.EmailPlus app. We're using version 4.0.0-dev-00218 of the plugin.

Any time it goes to send an email of an event matching the signals we have defined, it throws an exception and fails to send.

```
System.TypeInitializationException: The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
 ---> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load DLL 'System.IO.Compression.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits)
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at TimeZoneConverter.DataLoader.GetEmbeddedData(String resourceName)+MoveNext()
   at TimeZoneConverter.DataLoader.Populate(IDictionary`2 ianaMap, IDictionary`2 windowsMap, IDictionary`2 railsMap, IDictionary`2 inverseRailsMap)
   at TimeZoneConverter.TZConvert..cctor()
   --- End of inner exception stack trace ---
   at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)
   at Seq.App.EmailPlus.HandlebarsHelpers.DateTimeHelper(Context context, Arguments arguments) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\HandlebarsHelpers.cs:line 152
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method125(Closure, EncodedTextWriter&, BindingContext)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass19_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass20_0.<Compile>b__0(Object context, Object data)
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host, String dateTimeFormat, String timeZoneName) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 234
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 239
   at Seq.App.EmailPlus.EmailApp.OnAsync(Event`1 evt) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 154
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113
```

**Comment by nblumhardt** [comment]
Thanks for the note! Are you on Windows or Linux?

I've just tried 4.0.0 of the email app (just released) on Windows with that Seq version and all appears okay - perhaps upgrading to 4.0.0 of the email app would be a good thing to try next?

**Comment by c0shea** [comment]
Running on Windows. I can try and see what happens.On Feb 23, 2023 4:51 PM, Nicholas Blumhardt ***@***.***> wrote:
Thanks for the note! Are you on Windows or Linux?
I've just tried 4.0.0 of the email app (just released) on Windows with that Seq version and all appears okay - perhaps upgrading to 4.0.0 of the email app would be a good thing to try next?

**Comment by c0shea** [comment]
I upgraded to 4.0.0 of the email app and I'm still getting the exception when it tries to send an email

```
System.TypeInitializationException: The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
 ---> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load DLL 'System.IO.Compression.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits)
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at TimeZoneConverter.DataLoader.GetEmbeddedData(String resourceName)+MoveNext()
   at TimeZoneConverter.DataLoader.Populate(IDictionary`2 ianaMap, IDictionary`2 windowsMap, IDictionary`2 railsMap, IDictionary`2 inverseRailsMap)
   at TimeZoneConverter.TZConvert..cctor()
   --- End of inner exception stack trace ---
   at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)
   at Seq.App.EmailPlus.HandlebarsHelpers.DateTimeHelper(Context context, Arguments arguments) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\HandlebarsHelpers.cs:line 152
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method125(Closure, EncodedTextWriter&, BindingContext)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass19_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass20_0.<Compile>b__0(Object context, Object data)
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host, String dateTimeFormat, String timeZoneName) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 234
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 239
   at Seq.App.EmailPlus.EmailApp.OnAsync(Event`1 evt) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 154
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113
```

**Comment by nblumhardt** [comment]
Ah, interesting - thanks for the extra info.

I think this is a limitation in Seq's app loader that is being triggered by the new date/time formatting functions in 4.0 depending on some platform-specific binaries.

Strange that it wouldn't be reproducible on our test Windows box 🤔 - it could be something to do with the template, are you using the default body template?

Might also help to know the Windows version etc.; if you're able to shoot a diagnostic report through to support@ we can dig in deeper there. Thanks!

**Comment by c0shea** [comment]
Yes, I'm using the default template. Running on Windows Server 2012 R2.I didn't think it would, but I also tried installing .NET 6 and 7 runtimes on the server and that didn't make a difference.I did notice that the nupkg targets netstandard2.0 and net6 but not net7 yet the missing dll in the Seq install folder is for net7.On Feb 24, 2023 8:29 PM, Nicholas Blumhardt ***@***.***> wrote:

Ah, interesting - thanks for the extra info.

I think this is a limitation in Seq's app loader that is being triggered by the new date/time formatting functions in 4.0 depending on some platform-specific binaries.

Strange that it wouldn't be reproducible on our test Windows box 🤔 - it could be something to do with the template, are you using the default body template?

Might also help to know the Windows version etc.; if you're able to shoot a diagnostic report through to support@ we can dig in deeper there. Thanks!

**Comment by nblumhardt** [comment]
Thanks for following up with all of the info 👍 

I'm reasonably sure the problem is OS-dependent; this ticket is tracking the basic problem that will be the root cause:

https://github.com/datalust/seqcli/issues/252

I will need to dig into that ticket to determine how much time a fix is going to require; I'll post an update as soon as I have more info.

In the meantime, using the "Manage" link to roll back the version of the HTML email app you're using might be the only quick workaround, unfortunately.

**Comment by c0shea** [comment]
Thanks! I'm not sure which version I'd rollback the HTML email app to, though. Both the dev and 4.0.0 version fail for me. That only started happening when I upgraded Seq from 2022.1 (I think it was 7929) to 2023.1.8948

**Comment by nblumhardt** [comment]
I think `3.1.1-dev-00213` pre-dates any use of the functions that will cause the error; let me know if you still hit problems with that version.

**Comment by c0shea** [comment]
`3.1.1-dev-00213` is working for me until this is fixed. Thanks!

**Comment by nblumhardt** [comment]
Hi @c0shea, we've cooked up a couple of theories about how this might be happening, and published build `4.0.1-dev-00224` to try them out.

If it's possible to update to this build, it'd be great to hear whether the issue is resolved. Thanks!

**Comment by c0shea** [comment]
I installed the latest update. It seems promising! I haven't had any events come through the signals setup for the instances I have of the email app yet, but I did create a test instance of the app and manually send an event from the stream to it and it worked (where it previously didn't). I should have some events come through email overnight so I'll check back with you tomorrow. Thanks 😀

**Comment by nblumhardt** [comment]
Great! Thanks @c0shea 👍

**Comment by parion** [comment]
Hi, not @c0shea, but been having the same problem and was redirected here from this thread.
https://github.com/datalust/seq-tickets/discussions/1795#discussioncomment-5339260

I installed `4.0.1-dev-00224` but I am still running into the same exact issue as described above. The only app settings I have altered in my email instance are the from/to address and the host name. I am running Seq v2023.1.9101 on a localhost instance.

**Comment by nblumhardt** [comment]
Hi @parion, thanks for letting us know. I'll loop back around to this ASAP.

There's another workaround mentioned a few posts up, in case that helps unblock things in the meantime.

**Comment by c0shea** [comment]
@nblumhardt Build `4.0.1-dev-00224` seems to have done the trick for us. All of our alerts were successfully emailed overnight and I haven't seen any type initializer exceptions. Thanks!

**Comment by nblumhardt** [comment]
Thanks @c0shea!

Now it seems we have an even more puzzling question to solve - how did the `-dev` build fix the issue for one install, and not for the other? 🤔

**Comment by joedirt** [comment]
Adding a note from other discussion, this is occurring today on my install where I have the updated version.

**Comment by nblumhardt** [comment]
Thanks @joedirt. As it was unclear in the other thread, can you please also confirm the Seq version that you're running ("Support" menu in main navbar), and also include the exception message and stack trace from the app diagnostic message in Seq? Thanks again!

**Comment by joedirt** [comment]
Seq Version: 2023.1.9101
Html App Version: 4.0.1-dev-00224
Stack Trace:
System.TypeInitializationException: The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
 ---> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load DLL 'System.IO.Compression.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits)
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at TimeZoneConverter.DataLoader.GetEmbeddedData(String resourceName)+MoveNext()
   at TimeZoneConverter.DataLoader.Populate(IDictionary`2 ianaMap, IDictionary`2 windowsMap, IDictionary`2 railsMap, IDictionary`2 inverseRailsMap, IDictionary`2 links, IDictionary`2 ianaTerritoryZones)
   at TimeZoneConverter.TZConvert..cctor()
   --- End of inner exception stack trace ---
   at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)
   at Seq.App.EmailPlus.HandlebarsHelpers.DateTimeHelper(Context context, Arguments arguments) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\HandlebarsHelpers.cs:line 152
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method133(Closure, EncodedTextWriter&, BindingContext)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass19_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass20_0.<Compile>b__0(Object context, Object data)
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host, String dateTimeFormat, String timeZoneName) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 234
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 239
   at Seq.App.EmailPlus.EmailApp.OnAsync(Event`1 evt) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 154
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113

**Comment by n1njab0b** [comment]
Hey guys, same issue here:

Seq Version: Seq 2023.1.9101
HTML App Version: 4.0.1-dev-00224
OS: Windows Server 2019
Stack trace:


System.TypeInitializationException: The type initializer for 'TimeZoneConverter.TZConvert' threw an exception.
 ---> System.IO.Compression.ZLibException: The underlying compression routine could not be loaded correctly.
 ---> System.DllNotFoundException: Unable to load DLL 'System.IO.Compression.Native' or one of its dependencies: The specified module could not be found. (0x8007007E)
   at System.IO.Compression.ZLibNative.ZLibStreamHandle.InflateInit2_(Int32 windowBits)
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   --- End of inner exception stack trace ---
   at System.IO.Compression.Inflater.InflateInit(Int32 windowBits)
   at System.IO.Compression.DeflateStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen, Int32 windowBits, Int64 uncompressedSize)
   at System.IO.Compression.GZipStream..ctor(Stream stream, CompressionMode mode, Boolean leaveOpen)
   at TimeZoneConverter.DataLoader.GetEmbeddedData(String resourceName)+MoveNext()
   at TimeZoneConverter.DataLoader.Populate(IDictionary`2 ianaMap, IDictionary`2 windowsMap, IDictionary`2 railsMap, IDictionary`2 inverseRailsMap, IDictionary`2 links, IDictionary`2 ianaTerritoryZones)
   at TimeZoneConverter.TZConvert..cctor()
   --- End of inner exception stack trace ---
   at TimeZoneConverter.TZConvert.GetTimeZoneInfo(String windowsOrIanaTimeZoneId)
   at Seq.App.EmailPlus.HandlebarsHelpers.DateTimeHelper(Context context, Arguments arguments) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\HandlebarsHelpers.cs:line 152
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at HandlebarsDotNet.Helpers.DelegateReturnHelperDescriptor.HandlebarsDotNet.Helpers.IHelperDescriptor<HandlebarsDotNet.HelperOptions>.Invoke(EncodedTextWriter& output, HelperOptions& options, Context& context, Arguments& arguments)
   at lambda_method133(Closure, EncodedTextWriter&, BindingContext)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass19_0.<Compile>b__0(TextWriter writer, Object context, Object data)
   at HandlebarsDotNet.HandlebarsEnvironment.<>c__DisplayClass20_0.<Compile>b__0(Object context, Object data)
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host, String dateTimeFormat, String timeZoneName) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 234
   at Seq.App.EmailPlus.EmailApp.FormatTemplate(HandlebarsTemplate`2 template, Event`1 evt, Host host) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 239
   at Seq.App.EmailPlus.EmailApp.OnAsync(Event`1 evt) in C:\projects\seq-app-htmlemail\src\Seq.App.EmailPlus\EmailApp.cs:line 154
   at SeqCli.Apps.Hosting.AppContainer.SendTypedEventAsync(String clef) in C:\projects\seqcli\src\SeqCli\Apps\Hosting\AppContainer.cs:line 113

**Comment by nblumhardt** [comment]
Currently working on one possible solution; 👀 welcome over there :-) https://github.com/datalust/seq-app-htmlemail/issues/105

**Comment by nblumhardt** [comment]
Hi all!

Version [5.0.0-dev-00231](https://www.nuget.org/packages/Seq.App.EmailPlus/5.0.0-dev-00231) has now been published. This makes some compromises - on Windows, IANA time zone names are no longer supported in Seq versions before 2023.1, and Windows Server versions before 2019, but the implementation also no longer needs additional DLLs to be present, so this issue is fixed.

If you have any trouble at all with `5.0.0-dev-00231`, please let me know ASAP; we're aiming to mark this "stable" to replace 4.0.0 in the next week or two.

Thanks again for all your help tracking this issue down and getting to (what I hope is) a solid resolution :-)

Nick

**Comment by c0shea** [comment]
I upgraded to `5.0.0-dev-00231` and it's working for me. Thanks!

**Comment by joedirt** [comment]
Just upgraded, and it's working.  Thanks!
