### ISSUE TITLE
MissingMethodException in latest version

### ISSUE THREAD

**Issue by tonyt73** [datalust/seq-apps#18]
I get this error when running the replication app in Seq. (3.3.12-pre)
`2016-08-24 22:01:28.480 +00:00 [Information] Updated "appinstance-232"
2016-08-24 22:01:28.841 +00:00 [Error] Failed to load "Big Red Box (preprod)"
System.MissingMethodException: Method not found: 'Serilog.LoggerConfiguration Serilog.SeqLoggerConfigurationExtensions.Seq(Serilog.Configuration.LoggerSinkConfiguration, System.String, Serilog.Events.LogEventLevel, Int32, System.Nullable`1<System.TimeSpan>, System.String, System.String, System.Nullable`1<Int64>)'.
   at Seq.App.Replication.Replicator.OnAttached()
   at Seq.Server.Features.Runner.AppHost..ctor(ILogger logger, Func`2 createReactorInstance, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.AppHost..ctor(IInternalEventPublisher publisher, HostedApp hostedApp, AppInstance appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.SandboxedAppContainer.Initialize(IInternalEventPublisher publisher, String hostedApp, String appInstance, AppHostSettings settings)
   at Seq.Server.Features.Runner.RunningApp.LoadSandboxedAppContainer(AppDomain domain, HostedApp app)
   at Seq.Server.Features.Runner.RunningApp.Run()`

**Comment by nblumhardt** [comment]
Thanks for the report. The Replication app needs to be updated for Serilog 2.0/Serilog.Sinks.Seq 2.0, I've just tested this out locally and will push 2.0 versions of all of the app packages shortly.

**Comment by nblumhardt** [comment]
This will be a breaking change for the File Archive and Replication packages, which depend on types that have moved or changed signature in Serilog 2.0. For these packages, earlier versions of Seq will need to use the 1.x series of releases.
