### ISSUE TITLE
Email+ The app host process is stopped

### ISSUE THREAD

**Issue by jcmaglio** [datalust/seq-apps#66]
After updating some settings on our Email+ app instances, all the app processes have started to fail reporting the message _The app host process is stopped_.

Seq version: 5.1.3004
Email+ version: 2.0.92

The log reports the following error:
System.MissingMethodException: Method not found: 'Serilog.Events.LogEvent Serilog.Formatting.Compact.Reader.LogEventReader.ReadFromJObject(Newtonsoft.Json.Linq.JObject)'.
   at Seq.Apps.GenericHost.AppHost.ReadSerilogEvent(String clef, String& eventId, UInt32& eventType)
   at Seq.Apps.GenericHost.AppHost.<SendTypedEventAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Apps.GenericHost.AppHost.<SendAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Seq.Apps.GenericHost.Program.<Main>d__0.MoveNext()

Any idea about what could be the reason?
Thanks in advance

**Comment by nblumhardt** [comment]
Hi - thanks for your message.

The first thing I'd try, if possible, is updating to Seq 5.1.3364 - although it's not a fix we've recorded between those two versions, there's a chance that the installer will sort out any dependency issues.

Is there any chance that _Newtonsoft.Json.dll_ or _Serilog.*.dll_ has ended up in the GAC on the machine? You can check this by searching `%WINDIR%\Microsoft.NET\Assembly` on the server. These will cause problems, if so.

Let me know if either of the above helps!

Best regards,
Nick

**Comment by jcmaglio** [comment]
Dear Nick, 

after restarting the seq service all the app instances were working fine. Since we cannot update to the latest version at the moment, we think that this is enough to close the issue. 

Thanks a lot for the support

**Comment by nblumhardt** [comment]
Thanks for the follow-up, glad this resolved it :+1:
